(() => {
  "use strict";
  const AUTH={username:"edumind",password:"akds-pg-ksp092026"};
  const SESSION_KEY="akds_pg_ksp_session_v2",DRAFT_KEY="akds_pg_ksp_draft_v2";
  const STEPS=[{id:1,label:"Profil",cls:"s1"},{id:2,label:"Analisis",cls:"s2"},{id:3,label:"Arah Kurikulum",cls:"s3"},{id:4,label:"Pengorganisasian",cls:"s4"},{id:5,label:"Pembelajaran",cls:"s5"},{id:6,label:"Evaluasi",cls:"s6"},{id:7,label:"Hasil",cls:"s7"}];
  const LEVELS={kemendikdasmen:["SD","SMP","SMA"],kemenag:["MI","MTs","MA"]};
  const SOURCES=["Rapor Pendidikan","Asesmen Internal","Observasi Pembelajaran","Refleksi Guru","Survei Peserta Didik","Masukan Orang Tua","Data Prestasi","Data Sarana-Prasarana"];
  const PARTNERS=["Orang Tua","Komite","Pemerintah Daerah","Puskesmas/Layanan Kesehatan","Perguruan Tinggi","Dunia Usaha/Industri","Lembaga Keagamaan","Komunitas"];
  const PROFILES=["Keimanan dan ketakwaan terhadap Tuhan Yang Maha Esa","Kewargaan","Penalaran kritis","Kreativitas","Kolaborasi","Kemandirian","Kesehatan","Komunikasi"];
  const PANCA=["Cinta Allah dan Rasul-Nya","Cinta Ilmu","Cinta Lingkungan","Cinta Diri dan Sesama","Cinta Tanah Air"];
  const SPECIAL_PROGRAMS=["Literasi","Numerasi","Sains","Bahasa","Digital","Riset","Kewirausahaan","Tahfiz/Tahsin","Diniyah","Program Karakter/Adab"];
  const EXTRA=["Pramuka/Kepanduan","Olahraga","Seni","Keagamaan","Sains/Olimpiade","Teknologi","Bahasa","PMR/Kesehatan","Kewirausahaan"];
  const LEARNING=["Kontekstual","Pemecahan Masalah","Kolaboratif","Inkuiri/Eksplorasi","Projek","Refleksi","Diferensiasi","Literasi","Numerasi","Pemanfaatan Digital"];
  const ASSESSMENTS=["Asesmen Awal","Asesmen Formatif","Asesmen Sumatif","Portofolio","Projek/Kinerja","Refleksi Peserta Didik","Umpan Balik"];
  const EVAL_SOURCES=["Rapor Pendidikan/EDM","Hasil Belajar","Observasi","Supervisi","Refleksi Guru","Masukan Peserta Didik","Masukan Orang Tua","Evaluasi Program"];
  const GTK_DEV=["Pembelajaran Mendalam","Asesmen","Literasi & Numerasi","Teknologi/AI","Inklusi","Pengelolaan Kelas","Kepemimpinan Pembelajaran"];
  const DEV_FORMS=["Workshop","Pelatihan","Komunitas Belajar","Coaching/Mentoring","Supervisi Akademik","Belajar Mandiri"];
  const DOC_ELEMENTS=["Sampul","Identitas Satuan Pendidikan","Lembar Penetapan","Kata Pengantar","Daftar Isi","Acuan Pengembangan","Tabel Analisis","Tabel Program","Tabel Evaluasi","Lampiran"];
  const REGULATIONS={
    kemendikdasmen:["Permendikbudristek Nomor 12 Tahun 2024 tentang Kurikulum sebagaimana diubah dengan Permendikdasmen Nomor 13 Tahun 2025","Permendikdasmen Nomor 10 Tahun 2025 tentang Standar Kompetensi Lulusan","Permendikdasmen Nomor 12 Tahun 2025 tentang Standar Isi","Permendikdasmen Nomor 1 Tahun 2026 tentang Standar Proses","Permendikdasmen Nomor 26 Tahun 2025 tentang Standar Pengelolaan","Panduan Pengembangan Kurikulum Satuan Pendidikan Edisi Revisi 2025","Panduan Pembelajaran dan Asesmen Edisi Revisi 2025","Panduan Kokurikuler 2025"],
    kemenag:["KMA Nomor 450 Tahun 2024 sebagaimana diubah dengan KMA Nomor 1503 Tahun 2025","Keputusan Direktur Jenderal Pendidikan Islam Nomor 6077 Tahun 2025 tentang Panduan Kurikulum Berbasis Cinta","Panduan Kurikulum Madrasah, Panduan Pembelajaran dan Asesmen Madrasah, serta Panduan Kokurikuler Madrasah yang relevan"]
  };
  let currentStep=1,draftTimer=null,state={};
  const $=id=>document.getElementById(id),q=sel=>document.querySelector(sel),qa=sel=>[...document.querySelectorAll(sel)];

  function init(){renderStepper();renderStaticChoices();renderVmtBlocks();bindEvents();loadDraft();if(sessionStorage.getItem(SESSION_KEY)==="active")showApp();else showLogin();syncConditionalUI();updateAll()}
  function showLogin(){$("loginScreen").classList.remove("hidden");$("appScreen").classList.add("hidden");$("resultScreen").classList.add("hidden")}
  function showApp(){$("loginScreen").classList.add("hidden");$("resultScreen").classList.add("hidden");$("appScreen").classList.remove("hidden");showStep(currentStep)}
  function showResult(){$("loginScreen").classList.add("hidden");$("appScreen").classList.add("hidden");$("resultScreen").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
  function renderStepper(){$("desktopStepper").innerHTML=STEPS.map(s=>`<div class="step-item ${s.cls}" data-step-tab="${s.id}">${s.id}. ${s.label}</div>`).join("")}
  function checkboxHtml(name,value,label=value,checked=false){return `<label class="check-item"><input type="checkbox" name="${name}" value="${esc(value)}" ${checked?"checked":""}><span>${esc(label)}</span></label>`}
  function profileHtml(name,value){return `<label class="profile-item"><input type="checkbox" name="${name}" value="${esc(value)}"><span>⭐ ${esc(value)}</span></label>`}
  function renderStaticChoices(){
    $("sourceDataChoices").innerHTML=SOURCES.map(v=>checkboxHtml("sourceData",v)).join("");
    $("partnerChoices").innerHTML=PARTNERS.map(v=>checkboxHtml("partners",v)).join("");
    $("graduateProfileChoices").innerHTML=PROFILES.map(v=>profileHtml("graduatePriorities",v)).join("");
    $("pancaCintaChoices").innerHTML=PANCA.map(v=>profileHtml("pancaPriorities",v)).join("");
    $("specialProgramChoices").innerHTML=SPECIAL_PROGRAMS.map(v=>checkboxHtml("specialPrograms",v)).join("");
    $("extracurricularChoices").innerHTML=EXTRA.map(v=>checkboxHtml("extracurriculars",v)).join("");
    $("learningPracticeChoices").innerHTML=LEARNING.map(v=>checkboxHtml("learningPractices",v)).join("");
    $("assessmentChoices").innerHTML=ASSESSMENTS.map(v=>checkboxHtml("assessments",v)).join("");
    $("evaluationSourceChoices").innerHTML=EVAL_SOURCES.map(v=>checkboxHtml("evaluationSources",v)).join("");
    $("gtkDevelopmentChoices").innerHTML=GTK_DEV.map(v=>checkboxHtml("gtkDevelopment",v)).join("");
    $("developmentFormChoices").innerHTML=DEV_FORMS.map(v=>checkboxHtml("developmentForms",v)).join("");
    $("documentElementChoices").innerHTML=DOC_ELEMENTS.map(v=>checkboxHtml("docElements",v,v,true)).join("");
  }
  function renderVmtBlocks(){const blocks=[["vision","Visi"],["mission","Misi"],["goals","Tujuan"]];$("vmtBlocks").innerHTML=blocks.map(([key,label])=>`<div class="vmt-block"><div class="card-head"><h4>${label}</h4><span class="badge badge-ai">✨ Boleh Dibantu AI</span></div><div class="segmented"><label><input type="radio" name="${key}Mode" value="keep"><span>Pertahankan</span></label><label><input type="radio" name="${key}Mode" value="review"><span>Review & Sempurnakan</span></label><label><input type="radio" name="${key}Mode" value="generate" checked><span>Bantu Buat</span></label></div><div class="field-group"><label class="field-label" for="${key}Text">${label} Saat Ini</label><textarea id="${key}Text" rows="4" placeholder="Isi jika sudah tersedia. Jika memilih Bantu Buat, kolom ini boleh dikosongkan."></textarea><p class="helper" id="${key}Helper">AI akan menyusun usulan berdasarkan analisis karakteristik dan prioritas satuan pendidikan.</p></div></div>`).join("<div class='divider'></div>")}

  function bindEvents(){
    $("loginForm").addEventListener("submit",handleLogin);$("togglePassword").addEventListener("click",togglePassword);$("logoutBtn").addEventListener("click",logout);$("resultLogoutBtn").addEventListener("click",logout);$("prevStepBtn").addEventListener("click",()=>goToStep(currentStep-1));$("nextStepBtn").addEventListener("click",()=>goToStep(currentStep+1));$("generatePromptBtn").addEventListener("click",preGenerate);$("copyPromptBtn").addEventListener("click",copyPrompt);$("editDataBtn").addEventListener("click",backToEdit);$("backToEditBtn").addEventListener("click",backToEdit);$("startOverBtn").addEventListener("click",confirmReset);$("resetDraftBtn").addEventListener("click",confirmReset);$("showRegulationBtn").addEventListener("click",showRegulations);$("modalCloseBtn").addEventListener("click",closeModal);$("modalBackdrop").addEventListener("click",e=>{if(e.target===$("modalBackdrop"))closeModal()});document.addEventListener("change",onAnyInput);document.addEventListener("input",onAnyInput);qa("[data-step-tab]").forEach(el=>el.addEventListener("click",()=>{const step=Number(el.dataset.stepTab);if(step<=currentStep||step<=highestReachableStep())goToStep(step)}))
  }
  function handleLogin(e){e.preventDefault();const u=$("loginUsername").value.trim(),p=$("loginPassword").value;if(u===AUTH.username&&p===AUTH.password){$("loginError").classList.add("hidden");sessionStorage.setItem(SESSION_KEY,"active");showApp()}else $("loginError").classList.remove("hidden")}
  function togglePassword(){const f=$("loginPassword"),showing=f.type==="text";f.type=showing?"password":"text";$("togglePassword").textContent=showing?"👁️":"🙈";$("togglePassword").setAttribute("aria-label",showing?"Tampilkan password":"Sembunyikan password");$("togglePassword").title=showing?"Tampilkan password":"Sembunyikan password"}
  function logout(){sessionStorage.removeItem(SESSION_KEY);$("loginPassword").value="";showLogin()}
  function onAnyInput(e){if(!e.target.matches("input, select, textarea"))return;syncConditionalUI();collectState();scheduleSave();updateAll()}
  function goToStep(step){if(step<1)step=1;if(step>7)step=7;if(step>currentStep){const blockers=validateStep(currentStep);if(blockers.length){openModal("Lengkapi Data Wajib",`<div class="summary-list">${blockers.map(x=>row("err",x)).join("")}</div>`,[{label:"Tutup",cls:"btn btn-primary",action:closeModal}]);return}}currentStep=step;showStep(step)}
  function showStep(step){qa(".step-panel").forEach(p=>p.classList.toggle("hidden",Number(p.dataset.step)!==step));qa("[data-step-tab]").forEach(el=>{const n=Number(el.dataset.stepTab);el.classList.toggle("active",n===step);el.classList.toggle("done",n<step)});$("prevStepBtn").style.visibility=step===1?"hidden":"visible";$("nextStepBtn").classList.toggle("hidden",step===7);const pct=Math.round(step/7*100);$("mobileStepText").textContent=`Langkah ${step} dari 7 · ${STEPS[step-1].label}`;$("mobileStepPercent").textContent=`${pct}%`;$("mobileProgressBar").style.width=`${pct}%`;window.scrollTo({top:0,behavior:"smooth"})}
  function highestReachableStep(){let max=1;for(let s=1;s<=7;s++){if(validateStep(s).length===0)max=Math.max(max,s+1);else break}return Math.min(max,7)}

  function syncConditionalUI(){const ministry=getRadio("ministry");renderLevelChoices(ministry);$("nsmField").classList.toggle("hidden",ministry!=="kemenag");$("pancaCintaCard").classList.toggle("hidden",ministry!=="kemenag");$("kbcEvaluationField").classList.toggle("hidden",ministry!=="kemenag");if(ministry==="kemenag")ensureEdmOption();else removeEdmOption();const status=$("schoolStatus").value;$("foundationField").classList.toggle("hidden",status!=="Swasta");const cocMode=getRadio("cocurricularMode")||"ai";$("cocurricularExistingFields").classList.toggle("hidden",cocMode!=="existing");const mulok=getRadio("localContentStatus")||"no";$("localContentFields").classList.toggle("hidden",mulok!=="yes");["vision","mission","goals"].forEach(key=>{const mode=getRadio(`${key}Mode`)||"generate",helper=$(`${key}Helper`);if(!helper)return;helper.textContent=mode==="keep"?"AI akan menggunakan teks ini tanpa mengubah substansinya.":mode==="review"?"AI akan meninjau keselarasan dan menyempurnakan rumusan tanpa menghilangkan identitas utama.":"AI akan menyusun usulan berdasarkan analisis karakteristik dan prioritas satuan pendidikan."})}
  function ensureEdmOption(){if(!q('input[name="sourceData"][value="Evaluasi Diri Madrasah (EDM)"]'))$("sourceDataChoices").insertAdjacentHTML("beforeend",checkboxHtml("sourceData","Evaluasi Diri Madrasah (EDM)"))}
  function removeEdmOption(){const el=q('input[name="sourceData"][value="Evaluasi Diri Madrasah (EDM)"]');if(el)el.closest(".check-item")?.remove()}
  function renderLevelChoices(ministry){const wrap=$("levelChoices"),current=state.level||getRadio("level"),list=LEVELS[ministry]||[];wrap.innerHTML=list.map(level=>`<label class="chip ${current===level?"selected":""}"><input style="display:none" type="radio" name="level" value="${esc(level)}" ${current===level?"checked":""}>${esc(level)}</label>`).join("")||`<span class="helper">Pilih naungan terlebih dahulu.</span>`;wrap.querySelectorAll("input").forEach(i=>i.addEventListener("change",()=>{wrap.querySelectorAll(".chip").forEach(c=>c.classList.remove("selected"));i.closest(".chip").classList.add("selected");onAnyInput({target:i})}))}

  function validateStep(step){collectState();const b=[];if(step===1){if(!state.ministry)b.push("Pilih naungan satuan pendidikan.");if(!state.level)b.push("Pilih jenjang pendidikan.");if(!state.schoolName)b.push("Nama satuan pendidikan wajib diisi.");if(!state.academicYear)b.push("Tahun ajaran wajib diisi.")}if(step===2&&!state.studentCharacteristics)b.push("Karakteristik Peserta Didik wajib diisi.");if(step===3){["vision","mission","goals"].forEach(k=>{const mode=state[`${k}Mode`],text=state[`${k}Text`];if((mode==="keep"||mode==="review")&&!text)b.push(`${titleCase(k)} dipilih "${mode==="keep"?"Pertahankan":"Review & Sempurnakan"}", tetapi teks masih kosong.`)})}return b}

  function collectState(){state={ministry:getRadio("ministry"),level:getRadio("level"),schoolName:val("schoolName"),npsn:val("schoolNpsn"),nsm:val("schoolNsm"),schoolStatus:val("schoolStatus"),foundationName:val("foundationName"),province:val("province"),city:val("city"),academicYear:val("academicYear"),headName:val("headName"),accreditation:val("accreditation"),studentCount:val("studentCount"),rombelCount:val("rombelCount"),teacherCount:val("teacherCount"),staffCount:val("staffCount"),sourceData:checked("sourceData"),qualitySummary:val("qualitySummary"),studentCharacteristics:val("studentCharacteristics"),studentPotential:val("studentPotential"),learningNeeds:val("learningNeeds"),gtkCharacteristics:val("gtkCharacteristics"),gtkStrengths:val("gtkStrengths"),gtkNeeds:val("gtkNeeds"),facilities:val("facilities"),digitalLevel:val("digitalLevel"),communityContext:val("communityContext"),localPotential:val("localPotential"),partners:checked("partners"),otherPartners:val("otherPartners"),mainStrengths:val("mainStrengths"),mainChallenges:val("mainChallenges"),priorities:val("priorities"),analysisMethod:val("analysisMethod"),visionMode:getRadio("visionMode"),visionText:val("visionText"),missionMode:getRadio("missionMode"),missionText:val("missionText"),goalsMode:getRadio("goalsMode"),goalsText:val("goalsText"),graduatePriorities:checked("graduatePriorities"),pancaPriorities:checked("pancaPriorities"),organizationModel:val("organizationModel"),specialPrograms:checked("specialPrograms"),codingAiStatus:val("codingAiStatus"),cocurricularMode:getRadio("cocurricularMode"),cocurricularName:val("cocurricularName"),cocurricularGoal:val("cocurricularGoal"),cocurricularContext:val("cocurricularContext"),cocurricularSubjects:val("cocurricularSubjects"),cocurricularPartners:val("cocurricularPartners"),cocurricularTime:val("cocurricularTime"),cocurricularProduct:val("cocurricularProduct"),extracurriculars:checked("extracurriculars"),localContentStatus:getRadio("localContentStatus"),localContentName:val("localContentName"),localContentModel:val("localContentModel"),schoolCulture:val("schoolCulture"),learningPractices:checked("learningPractices"),assessments:checked("assessments"),assessmentPolicy:val("assessmentPolicy"),evaluationFrequency:val("evaluationFrequency"),evaluationSources:checked("evaluationSources"),gtkDevelopment:checked("gtkDevelopment"),developmentForms:checked("developmentForms"),kbcEvaluation:val("kbcEvaluation"),followUp:val("followUp"),depthMode:getRadio("depthMode"),outputMode:getRadio("outputMode"),docElements:checked("docElements"),specialInstructions:val("specialInstructions")};return state}
  function scheduleSave(){$("saveStatus").textContent="Menyimpan...";clearTimeout(draftTimer);draftTimer=setTimeout(()=>{localStorage.setItem(DRAFT_KEY,JSON.stringify({state,step:currentStep,updatedAt:Date.now()}));$("saveStatus").textContent="✓ Draft tersimpan"},450)}
  function loadDraft(){const raw=localStorage.getItem(DRAFT_KEY);if(!raw)return;try{const saved=JSON.parse(raw);if(!saved?.state)return;state=saved.state;currentStep=Number(saved.step)||1;hydrateState(saved.state);$("saveStatus").textContent="✓ Draft dipulihkan"}catch{}}
  function hydrateState(s){setRadio("ministry",s.ministry);syncConditionalUI();renderLevelChoices(s.ministry);setRadio("level",s.level);const map={schoolName:"schoolName",npsn:"schoolNpsn",nsm:"schoolNsm",schoolStatus:"schoolStatus",foundationName:"foundationName",province:"province",city:"city",academicYear:"academicYear",headName:"headName",accreditation:"accreditation",studentCount:"studentCount",rombelCount:"rombelCount",teacherCount:"teacherCount",staffCount:"staffCount",qualitySummary:"qualitySummary",studentCharacteristics:"studentCharacteristics",studentPotential:"studentPotential",learningNeeds:"learningNeeds",gtkCharacteristics:"gtkCharacteristics",gtkStrengths:"gtkStrengths",gtkNeeds:"gtkNeeds",facilities:"facilities",digitalLevel:"digitalLevel",communityContext:"communityContext",localPotential:"localPotential",otherPartners:"otherPartners",mainStrengths:"mainStrengths",mainChallenges:"mainChallenges",priorities:"priorities",analysisMethod:"analysisMethod",visionText:"visionText",missionText:"missionText",goalsText:"goalsText",organizationModel:"organizationModel",codingAiStatus:"codingAiStatus",cocurricularName:"cocurricularName",cocurricularGoal:"cocurricularGoal",cocurricularContext:"cocurricularContext",cocurricularSubjects:"cocurricularSubjects",cocurricularPartners:"cocurricularPartners",cocurricularTime:"cocurricularTime",cocurricularProduct:"cocurricularProduct",localContentName:"localContentName",localContentModel:"localContentModel",schoolCulture:"schoolCulture",assessmentPolicy:"assessmentPolicy",evaluationFrequency:"evaluationFrequency",kbcEvaluation:"kbcEvaluation",followUp:"followUp",specialInstructions:"specialInstructions"};Object.entries(map).forEach(([k,id])=>{if($(id)&&s[k]!==undefined)$(id).value=s[k]??""});["visionMode","missionMode","goalsMode","cocurricularMode","localContentStatus","depthMode","outputMode"].forEach(name=>setRadio(name,s[name]));setChecked("sourceData",s.sourceData);setChecked("partners",s.partners);setChecked("graduatePriorities",s.graduatePriorities);setChecked("pancaPriorities",s.pancaPriorities);setChecked("specialPrograms",s.specialPrograms);setChecked("extracurriculars",s.extracurriculars);setChecked("learningPractices",s.learningPractices);setChecked("assessments",s.assessments);setChecked("evaluationSources",s.evaluationSources);setChecked("gtkDevelopment",s.gtkDevelopment);setChecked("developmentForms",s.developmentForms);setChecked("docElements",s.docElements);syncConditionalUI()}

  function updateAll(){collectState();updateHeader();updateCompletion();updateWarnings();updateGenerateLabel()}
  function updateHeader(){const ministryName=state.ministry==="kemenag"?"Kurikulum Madrasah":state.ministry==="kemendikdasmen"?"Kurikulum Satuan Pendidikan":"KSP & Kurikulum Madrasah";$("appSubtitle").textContent=ministryName;const badges=[];if(state.ministry)badges.push(state.ministry==="kemenag"?"Kemenag":"Kemendikdasmen");if(state.level)badges.push(state.level);if(state.academicYear)badges.push(state.academicYear);$("activeProfileBadges").innerHTML=badges.length?badges.map(b=>`<span class="badge">${esc(b)}</span>`).join(""):`<span class="badge">Belum dipilih</span>`}
  function completionScore(){const groups=[{w:15,vals:[state.ministry,state.level,state.schoolName,state.academicYear]},{w:25,vals:[state.studentCharacteristics,state.qualitySummary,state.mainStrengths,state.mainChallenges,state.priorities]},{w:15,vals:[state.visionMode,state.missionMode,state.goalsMode,state.graduatePriorities?.length]},{w:15,vals:[state.organizationModel,state.cocurricularMode,state.extracurriculars?.length,state.localContentStatus]},{w:15,vals:[state.learningPractices?.length,state.assessments?.length,state.digitalLevel]},{w:10,vals:[state.evaluationFrequency,state.evaluationSources?.length,state.gtkDevelopment?.length]},{w:5,vals:[state.depthMode,state.outputMode,state.docElements?.length]}];let total=0;groups.forEach(g=>{const done=g.vals.filter(v=>Array.isArray(v)?v.length:!!v).length;total+=g.w*(done/g.vals.length)});return Math.round(total)}
  function updateCompletion(){const pct=completionScore();$("completionPercent").textContent=`${pct}%`;$("completionBar").style.width=`${pct}%`;$("completionText").textContent=pct>=85?"Siap":pct>=60?"Cukup":"Belum lengkap";const items=[["Profil dasar",!!(state.ministry&&state.level&&state.schoolName&&state.academicYear)],["Analisis karakteristik",!!state.studentCharacteristics],["Arah kurikulum",!!(state.visionMode&&state.missionMode&&state.goalsMode)],["Pengorganisasian",!!(state.organizationModel||state.cocurricularMode)],["Pembelajaran & asesmen",!!((state.learningPractices||[]).length||(state.assessments||[]).length)],["Evaluasi",!!state.evaluationFrequency],["Preferensi output",!!(state.depthMode&&state.outputMode)]];$("completionDetails").innerHTML=items.map(([label,ok])=>row(ok?"ok":"warn",`${ok?"✓":"○"} ${label}`)).join("")}
  function warningList(){const w=[];if(!state.qualitySummary)w.push("Data mutu/Rapor Pendidikan/EDM belum diisi.");if(!state.mainStrengths||!state.mainChallenges)w.push("Kekuatan atau tantangan utama masih terbatas.");["vision","mission","goals"].forEach(k=>{if(state[`${k}Mode`]==="generate"&&!state[`${k}Text`])w.push(`${titleCase(k)} akan dibuat sebagai usulan AI.`)});if(state.outputMode==="docx"||state.outputMode==="chat_docx")w.push("Pembuatan DOCX bergantung pada kemampuan AI tujuan.");return w}
  function updateWarnings(){const w=warningList();$("liveWarnings").innerHTML=w.length?w.slice(0,5).map(x=>row("warn",`⚠ ${x}`)).join(""):row("ok","✓ Tidak ada catatan penting.")}
  function updateGenerateLabel(){const doc=state.ministry==="kemenag"?"Kurikulum Madrasah":"KSP";$("generatePromptBtn").textContent=`✨ Hasilkan Prompt ${doc}`;$("generateTitle").textContent=`Siap menghasilkan Prompt ${doc}`}

  function preGenerate(){collectState();const blockers=[...validateStep(1),...validateStep(2),...validateStep(3)];if(blockers.length){openModal("Data Wajib Belum Lengkap",`<div class="summary-list">${[...new Set(blockers)].map(x=>row("err",x)).join("")}</div>`,[{label:"Kembali & Perbaiki",cls:"btn btn-primary",action:closeModal}]);return}const warnings=warningList();const html=`<div class="summary-list">${row("ok","✓ Profil regulasi sudah lengkap")}${row("ok","✓ Identitas utama tersedia")}${warnings.map(x=>row("warn",`⚠ ${x}`)).join("")}${row("ok",`✓ Kedalaman dokumen: ${esc(state.depthMode||"Standar")}`)}</div><p class="helper" style="margin-top:14px">Anda tetap dapat melanjutkan. AI tidak akan mengarang data yang belum tersedia.</p>`;openModal("Periksa Sebelum Menghasilkan Prompt",html,[{label:"Kembali & Perbaiki",cls:"btn btn-ghost",action:closeModal},{label:"Hasilkan Prompt",cls:"btn btn-success",action:generatePrompt}])}
  function generatePrompt(){closeModal();collectState();$("promptOutput").textContent=compilePrompt(state);renderResultSummary();showResult()}
  function compilePrompt(s){const ministryName=s.ministry==="kemenag"?"Kementerian Agama":"Kementerian Pendidikan Dasar dan Menengah",docName=s.ministry==="kemenag"?"Kurikulum Madrasah":"Kurikulum Satuan Pendidikan (KSP)",lines=[];
    pushSection(lines,"PERAN DAN TUGAS",[`Anda bertindak sebagai ahli pengembangan kurikulum pendidikan Indonesia yang memahami perencanaan berbasis data, Pembelajaran Mendalam, pengorganisasian pembelajaran, asesmen, kokurikuler, evaluasi kurikulum, dan pengembangan profesional pendidik${s.ministry==="kemenag"?", termasuk Kurikulum Berbasis Cinta":""}.`,`Susun DRAF ${docName} yang kontekstual, substantif, operasional, berbasis data, dan mudah ditinjau oleh satuan pendidikan.`,`Dokumen bukan sekadar pemenuhan administrasi. Prioritaskan kebutuhan murid, karakteristik satuan pendidikan, keterlaksanaan program, konsistensi antarkomponen, dan peningkatan mutu berkelanjutan.`]);
    pushSection(lines,"REGULATORY PROFILE",[`Naungan: ${ministryName}`,`Jenjang: ${s.level}`,`Tahun Ajaran: ${s.academicYear}`,`Nama dokumen: ${docName}`,"","Gunakan acuan utama berikut:",...REGULATIONS[s.ministry].map(x=>`- ${x}`),"","Gunakan ketentuan paling baru apabila ketentuan lama telah diubah, diganti, atau disesuaikan. Jangan menggunakan nomenklatur lama sebagai struktur utama hanya karena masih banyak ditemukan dalam dokumen lama di internet."]);
    pushSection(lines,"ATURAN KERAS",["Bedakan informasi menjadi FACT, REGULATORY, dan RECOMMENDATION.","FACT hanya boleh berasal dari data pengguna. Jangan menebak atau membuat fakta baru.","RECOMMENDATION harus jelas sebagai usulan, bukan program yang seolah-olah sudah dilaksanakan.","Jangan mengarang NPSN/NSM, jumlah murid/guru, akreditasi, skor Rapor Pendidikan/EDM, program existing, fasilitas, mitra, alokasi JP, nama pejabat, NIP, nomor SK/surat, tanggal penetapan, kutipan regulasi, pasal, atau data faktual lain yang tidak diberikan.","Jika data penting tidak tersedia, hilangkan rinciannya atau gunakan placeholder yang spesifik seperti [DATA PERLU DILENGKAPI: NPSN].","Jangan mengubah FACT pengguna hanya agar dokumen tampak lebih konsisten."]);
    pushSection(lines,"DATA SATUAN PENDIDIKAN",compact([`Nama satuan pendidikan: ${s.schoolName}`,maybe("NPSN",s.npsn),s.ministry==="kemenag"?maybe("NSM",s.nsm):"",maybe("Status",s.schoolStatus),maybe("Yayasan",s.foundationName),maybe("Provinsi",s.province),maybe("Kabupaten/Kota",s.city),maybe("Kepala Satuan Pendidikan",s.headName),maybe("Akreditasi",s.accreditation),maybe("Jumlah peserta didik",s.studentCount),maybe("Jumlah rombongan belajar",s.rombelCount),maybe("Jumlah guru",s.teacherCount),maybe("Jumlah tenaga kependidikan",s.staffCount)]));
    const partners=[...(s.partners||[])];if(s.otherPartners)partners.push(s.otherPartners);
    pushSection(lines,"ANALISIS KARAKTERISTIK",compact([arr("Sumber data",s.sourceData),maybe("Ringkasan data mutu",s.qualitySummary),maybe("Karakteristik peserta didik",s.studentCharacteristics),maybe("Potensi/minat/bakat",s.studentPotential),maybe("Kebutuhan belajar utama",s.learningNeeds),maybe("Karakteristik GTK",s.gtkCharacteristics),maybe("Kekuatan GTK",s.gtkStrengths),maybe("Kebutuhan pengembangan GTK",s.gtkNeeds),maybe("Sarana dan prasarana",s.facilities),maybe("Tingkat pemanfaatan teknologi",s.digitalLevel),maybe("Karakteristik lingkungan/masyarakat",s.communityContext),maybe("Potensi/kearifan lokal",s.localPotential),arr("Kemitraan",partners),maybe("Kekuatan utama",s.mainStrengths),maybe("Tantangan utama",s.mainChallenges),maybe("Prioritas pengembangan",s.priorities),maybe("Metode analisis",s.analysisMethod),"","Lakukan analisis internal dengan alur DATA → KEKUATAN → TANTANGAN → KEBUTUHAN → PRIORITAS → STRATEGI → IMPLEMENTASI → EVALUASI. Jangan membuat kesimpulan yang tidak didukung data pengguna."]));
    pushSection(lines,"VISI, MISI, DAN TUJUAN",[...vmtInstruction("Visi",s.visionMode,s.visionText),"",...vmtInstruction("Misi",s.missionMode,s.missionText),"",...vmtInstruction("Tujuan",s.goalsMode,s.goalsText)]);
    pushSection(lines,"PROFIL LULUSAN",["Gunakan keseluruhan delapan Dimensi Profil Lulusan:",...PROFILES.map((x,i)=>`${i+1}. ${x}`),"",arr("Fokus penguatan pengguna",s.graduatePriorities)||"Fokus penguatan pengguna: tidak ditentukan secara khusus.","Pilihan fokus tidak berarti dimensi lain tidak berlaku. Seluruh delapan dimensi tetap menjadi kerangka."]);
    if(s.ministry==="kemenag")pushSection(lines,"KURIKULUM BERBASIS CINTA",["Integrasikan lima Panca Cinta:",...PANCA.map((x,i)=>`${i+1}. ${x}`),"",arr("Fokus penguatan Panca Cinta",s.pancaPriorities)||"Fokus penguatan Panca Cinta: tidak ditentukan secara khusus.","Panca Cinta bukan mata pelajaran tersendiri. Integrasikan secara proporsional melalui intrakurikuler, kokurikuler, ekstrakurikuler, serta budaya/iklim madrasah.","Jangan menambahkan program keagamaan yang tidak dinyatakan pengguna."]);
    pushSection(lines,"PENGORGANISASIAN PEMBELAJARAN",compact([maybe("Model pengorganisasian",s.organizationModel),arr("Program/kekhasan existing",s.specialPrograms),maybe("Status Koding dan Kecerdasan Artifisial",s.codingAiStatus),s.localContentStatus==="yes"?maybe("Muatan lokal",s.localContentName):"",s.localContentStatus==="yes"?maybe("Cara penyelenggaraan muatan lokal",s.localContentModel):"",maybe("Budaya/pembiasaan existing",s.schoolCulture),"Jangan mengarang alokasi JP. Jika data alokasi waktu tidak tersedia secara valid, gunakan keterangan bahwa struktur rinci perlu disesuaikan dengan ketentuan jenjang yang berlaku."]));
    const coco=[];if(s.cocurricularMode==="existing"){coco.push("Mode kokurikuler: program existing.");coco.push(...compact([maybe("Nama program",s.cocurricularName),maybe("Tujuan",s.cocurricularGoal),maybe("Tema/konteks",s.cocurricularContext),maybe("Mata pelajaran yang berkolaborasi",s.cocurricularSubjects),maybe("Mitra",s.cocurricularPartners),maybe("Perkiraan waktu",s.cocurricularTime),maybe("Hasil/produk yang diharapkan",s.cocurricularProduct)]));coco.push("Hanya data yang diberikan di atas yang boleh ditulis sebagai program existing.")}else{coco.push("Mode kokurikuler: BANTU AI MERANCANG.");coco.push("Rancang rekomendasi kokurikuler berdasarkan karakteristik, prioritas pengembangan, Profil Lulusan, potensi lokal, kemitraan, dan kondisi satuan pendidikan.");coco.push("Semua program yang dirancang AI harus jelas sebagai rekomendasi, bukan program existing.")}coco.push("Gunakan nomenklatur kokurikuler terbaru. Jangan otomatis menggunakan P5 atau P5RA sebagai struktur utama.");if(s.ministry==="kemenag")coco.push("Jika relevan, dapat gunakan Kegiatan Kolaboratif Berbasis Cinta.");pushSection(lines,"KOKURIKULER",coco);
    if((s.extracurriculars||[]).length)pushSection(lines,"EKSTRAKURIKULER",[arr("Program existing",s.extracurriculars),"Hubungkan secara proporsional dengan pengembangan murid dan Dimensi Profil Lulusan. Jangan menambahkan ekstrakurikuler lain sebagai fakta."]);
    pushSection(lines,"PEMBELAJARAN MENDALAM DAN ASESMEN",compact([arr("Praktik pembelajaran yang ingin dikuatkan",s.learningPractices),maybe("Tingkat pemanfaatan digital",s.digitalLevel),arr("Praktik asesmen",s.assessments),maybe("Kebijakan/kekhasan asesmen",s.assessmentPolicy),"","Gunakan prinsip Pembelajaran Mendalam: berkesadaran, bermakna, dan menggembirakan.","Gunakan pengalaman belajar: memahami, mengaplikasi, dan merefleksi.","Jelaskan implementasi secara operasional, bukan sebagai uraian teori panjang.","Jangan menghasilkan bank soal atau instrumen rinci per mata pelajaran."]));
    pushSection(lines,"EVALUASI DAN PENGEMBANGAN PROFESIONAL",compact([maybe("Frekuensi evaluasi",s.evaluationFrequency),arr("Sumber evaluasi",s.evaluationSources),arr("Prioritas pengembangan GTK",s.gtkDevelopment),arr("Bentuk pengembangan",s.developmentForms),s.ministry==="kemenag"?maybe("Evaluasi implementasi Panca Cinta",s.kbcEvaluation):"",maybe("Mekanisme tindak lanjut",s.followUp),"Susun mekanisme evaluasi yang menjelaskan fokus, indikator, sumber data, waktu, pihak/fungsi yang terlibat, dan tindak lanjut. Jika nama orang tidak tersedia, gunakan jabatan/fungsi, bukan nama fiktif."]));
    const docEls=s.docElements||[];pushSection(lines,"STRUKTUR DOKUMEN",[`Tingkat kedalaman: ${s.depthMode||"Standar"}.`,docEls.length?`Elemen yang diminta: ${docEls.join(", ")}.`:"","","Kerangka utama:","BAB I — Karakteristik Satuan Pendidikan/Madrasah","BAB II — Visi, Misi, dan Tujuan","BAB III — Pengorganisasian Pembelajaran","BAB IV — Perencanaan Pembelajaran","BAB V — Evaluasi, Pendampingan, dan Pengembangan Profesional","","Empat komponen minimum tetap: karakteristik; visi-misi-tujuan; pengorganisasian pembelajaran; perencanaan pembelajaran. Jangan menyatakan BAB V sebagai komponen minimum kelima.",s.ministry==="kemenag"?"Untuk madrasah, lampirkan beberapa contoh perencanaan pembelajaran representatif bila lampiran diminta, tanpa membuat seluruh perangkat semua kelas/mata pelajaran.":""]);
    const outputRules=[];if(s.outputMode==="chat")outputRules.push("Tampilkan dokumen lengkap dalam percakapan.");else if(s.outputMode==="docx")outputRules.push("Jika sistem AI mendukung pembuatan file, buat Microsoft Word (.docx) yang dapat diunduh. Jika tidak mendukung, jangan mengklaim file telah dibuat; berikan output Word-ready.");else outputRules.push("Tampilkan dokumen lengkap dalam percakapan dan, jika sistem AI mendukung, buat Microsoft Word (.docx) yang dapat diunduh. Jika tidak mendukung, jangan mengklaim file telah dibuat; berikan output Word-ready.");if(s.outputMode!=="chat")outputRules.push("Untuk DOCX gunakan A4, heading bertingkat, tabel editable, penomoran konsisten, nomor halaman, page break antarbagian utama, dan daftar isi otomatis bila didukung. Jangan membuat stempel, tanda tangan digital, NIP, nomor SK/surat, atau tanggal penetapan palsu.");if(s.specialInstructions)outputRules.push(`Instruksi khusus pengguna: ${s.specialInstructions}`);pushSection(lines,"OUTPUT",outputRules);
    pushSection(lines,"QUALITY CHECK SEBELUM HASIL AKHIR",["Periksa lima hal berikut secara internal:","1. Regulatory: kementerian, istilah, dan kerangka sudah sesuai.","2. Factual: tidak ada fakta yang dibuat atau ditebak.","3. Coherence: karakteristik → prioritas → program → pembelajaran → asesmen → evaluasi saling terhubung.","4. Scope: hasil tetap berupa KSP/Kurikulum Madrasah, bukan berubah menjadi perangkat pembelajaran lain.","5. Output: format sesuai pilihan pengguna dan DOCX hanya diklaim bila benar-benar dibuat.","",`Sekarang susun ${docName} untuk ${s.schoolName}, jenjang ${s.level}, Tahun Ajaran ${s.academicYear}. Gunakan bahasa formal, alami, profesional, kontekstual, tidak berulang, dan mudah diedit oleh tim satuan pendidikan.`]);return lines.filter(Boolean).join("\n")
  }
  function renderResultSummary(){collectState();const ministry=state.ministry==="kemenag"?"Kemenag":"Kemendikdasmen",out=state.outputMode==="chat"?"Chat":state.outputMode==="docx"?"DOCX":"Chat + DOCX",badges=[ministry,state.level,state.academicYear,state.depthMode,out].filter(Boolean);$("resultBadges").innerHTML=badges.map(b=>`<span class="badge">${esc(b)}</span>`).join("");$("resultSummaryList").innerHTML=[row("ok",`Dokumen: ${state.ministry==="kemenag"?"Kurikulum Madrasah":"KSP"}`),row("ok",`Kelengkapan input: ${completionScore()}%`),row("ok",`Kedalaman: ${state.depthMode}`),row("ok",`Output: ${out}`),row("warn",`${warningList().length} catatan sebelum generate`)].join("")}
  async function copyPrompt(){const text=$("promptOutput").textContent;try{await navigator.clipboard.writeText(text);showToast("✓ Prompt berhasil disalin");$("copyPromptBtn").textContent="✓ Tersalin";setTimeout(()=>$("copyPromptBtn").textContent="Salin Prompt",1800)}catch{showToast("Gagal menyalin otomatis. Silakan salin manual.")}}
  function backToEdit(){showApp()}
  function confirmReset(){openModal("Mulai Penyusunan Baru?","<p>Seluruh isian pada draft saat ini akan dihapus dari browser.</p>",[{label:"Batal",cls:"btn btn-ghost",action:closeModal},{label:"Ya, Mulai Ulang",cls:"btn btn-danger-soft",action:resetAll}])}
  function resetAll(){localStorage.removeItem(DRAFT_KEY);closeModal();location.reload()}
  function showRegulations(){collectState();const ministry=state.ministry;if(!ministry){openModal("Acuan Regulasi","<p>Pilih naungan satuan pendidikan terlebih dahulu.</p>",[{label:"Tutup",cls:"btn btn-primary",action:closeModal}]);return}const title=ministry==="kemenag"?"Kementerian Agama":"Kemendikdasmen",html=`<p><strong>Profil aktif:</strong> ${esc(title)}</p><div class="summary-list">${REGULATIONS[ministry].map(x=>row("ok",`✓ ${x}`)).join("")}</div><p class="helper" style="margin-top:14px"><strong>Terakhir diverifikasi:</strong> September 2026</p>`;openModal("Acuan Regulasi Aktif",html,[{label:"Tutup",cls:"btn btn-primary",action:closeModal}])}
  function openModal(title,content,actions=[]){$("modalTitle").textContent=title;$("modalContent").innerHTML=content;$("modalActions").innerHTML="";actions.forEach(a=>{const btn=document.createElement("button");btn.className=a.cls||"btn btn-primary";btn.textContent=a.label;btn.addEventListener("click",a.action);$("modalActions").appendChild(btn)});$("modalBackdrop").classList.remove("hidden")}
  function closeModal(){$("modalBackdrop").classList.add("hidden")}
  function showToast(msg){$("toast").textContent=msg;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2200)}
  function pushSection(lines,title,content){const c=(content||[]).filter(x=>x!==null&&x!==undefined&&String(x).trim()!=="");if(!c.length)return;lines.push("==================================================",title,"==================================================",...c,"")}
  function vmtInstruction(label,mode,text){const L=label.toUpperCase();if(mode==="keep")return[`${L} — MODE PERTAHANKAN`,text?`Teks existing: ${text}`:"","Pertahankan substansi dan redaksi. Jangan mengubahnya kecuali koreksi ejaan nyata bila diperlukan."].filter(Boolean);if(mode==="review")return[`${L} — MODE REVIEW & SEMPURNAKAN`,text?`Teks existing: ${text}`:"","Tinjau keselarasan dengan karakteristik, prioritas, dan Profil Lulusan. Sempurnakan secara proporsional tanpa menghilangkan identitas utama."].filter(Boolean);return[`${L} — MODE BANTU BUAT`,text?`Bahan awal pengguna: ${text}`:"",`Susun ${label.toLowerCase()} sebagai USULAN berdasarkan karakteristik, aspirasi, prioritas, dan Profil Lulusan. Jangan menyatakan usulan ini sebagai rumusan yang sudah ditetapkan.`].filter(Boolean)}
  function row(type,text){return `<div class="summary-row"><span class="${type}">●</span><span>${esc(text)}</span></div>`}
  function val(id){return($(id)?.value||"").trim()}function getRadio(name){return q(`input[name="${name}"]:checked`)?.value||""}function setRadio(name,value){if(!value)return;const els=qa(`input[name="${name}"]`),el=els.find(x=>x.value===value);if(el)el.checked=true}function checked(name){return qa(`input[name="${name}"]:checked`).map(x=>x.value)}function setChecked(name,values=[]){qa(`input[name="${name}"]`).forEach(x=>x.checked=(values||[]).includes(x.value))}function maybe(label,v){return v?`${label}: ${v}`:""}function arr(label,a){return a&&a.length?`${label}: ${a.join(", ")}`:""}function compact(a){return a.filter(x=>x!==null&&x!==undefined&&String(x).trim()!=="")}function titleCase(k){return({vision:"Visi",mission:"Misi",goals:"Tujuan"})[k]||k}function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
  document.addEventListener("DOMContentLoaded",init);
})();
